### ISSUE TITLE
can't work with reek 1.6.2 and 1.6.3

### ISSUE THREAD

**Issue by yangsr** [metricfu/metric_fu#239]
Hi ! 

Reek has updated to 1.6.2 on January 13, 2015,  https://rubygems.org/gems/reek

then I typed `metric_fu` in my project root, it  stopped at

`******* STARTING METRIC reek` 

for quite a long time.

I uninstall reek 1.6.2 and install reek 1.6.1, then everything goes OK.

**Comment by MGotink** [comment]
Reek 1.6.2 added a feature where you can pipe code directly to reek: https://github.com/troessner/reek/commit/81b2d4af816687386ab4d53c2ec0fae30f80f9d7#diff-05b3d9fdbeb4b51d9509f8eb17bc586eR10

Metric_fu uses Open3::popen3 which pipes stdin and thus creates a deadlock. AFAIK there is no way to circumvent this using Open3.

I'm not sure what will be the best way to solve this, maybe we can use reek directly as a library, @bf4 ideas?

**Comment by bf4** [comment]
Using reek as a library sounds great!

**Comment by MGotink** [comment]
Metric_fu 4.11.2 fixes this issue.
Thanks for reporting!
