### ISSUE TITLE
Reek doesn't finish to run any more in metric_fu 4.7.2

### ISSUE THREAD

**Issue by yohannes-l** [metricfu/metric_fu#241]
I am just about to upgrade a large application which run fine on metric_fu 4.4 for a long time
When upgrading to metric_fu 4.11. I realized that the CI process doesn't finish anymore because it stops at 
`******* STARTING METRIC reek`
The problem that reek takes too long and doesn't seem to finish occurs in my project for the metric_fu versions 4.7.2, 4.7.3, 4.7.4, 4.8, 4.9., 4.10, 4.11
On 4.7 and 4.7.1 it works

**Comment by MGotink** [comment]
This is an issue with reek > 1.6.1, see #240, #239.
It's fixed in metric_fu 4.11.2.

**Comment by yohannes-l** [comment]
super, thanks
