### ISSUE TITLE
Error: invalid option: --config lib/config/defaults.reek

### ISSUE THREAD

**Issue by yangsr** [metricfu/metric_fu#242]
Hi ! 

I want to include config file pattern into reek parameters. So I add the following code to my .metrics file
```
case metric.name
when :reek
  metric.config_file_pattern = 'lib/config/defaults.reek'
end
```
I copyed the `defaults.reek` file from https://github.com/troessner/reek/blob/master/config/defaults.reek

When I ran `metric_fu` in my rails console, it said:
```
******* STARTING METRIC reek
Error: invalid option: --config lib/config/defaults.reek
```
I download the reek, add `p @options` at line 20 of https://github.com/troessner/reek/blob/master/lib/reek/cli/application.rb
to test.

When I run `reek --no-line-numbers --config lib/config/defaults.reek` at my project's root

The `p @options` output is 
`<Reek::Cli::Options:0x00000002be2b00 @argv=["--no-line-numbers", "--config", "lib/config/defaults.reek", *balabala>`

but when I run `metric_fu`, the output is 
`#<Reek::Cli::Options:0x00000002be2b00 @argv=["--no-line-numbers", "--config lib/config/defaults.reek", *balabala>`

so I've found a bug here:
In the file: lib/metric_fu/metrics/reek/generator.rb
```
def config_option
  config_file_pattern =  options[:config_file_pattern]
  if config_file_pattern.to_s.empty?
    ''
  else
    "--config #{config_file_pattern}"
  end
end
```
This method returns `"--config lib/config/defaults.reek"`
But reek needs `"--config" "lib/config/defaults.reek"`
at line 26 of lib/metric_fu/metrics/reek/generator.rb, https://github.com/metricfu/metric_fu/pull/240/files
The args passed to reek now is `['--no-line-numbers', '--no-color', '--config lib/config/reek.yml']`
But for reek1.6.4, it actually needs `['--no-line-numbers', '--no-color', '--config', 'lib/config/reek.yml']`

**Comment by MGotink** [comment]
My bad :)
Thanks for reporting!
