### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by bf4** [metricfu/metric_fu#280]

**Comment by nirnaeth** [comment]
I hope I can help, what do you have in mind? should I just pick a random issue and try to solve it, do you need help reviewing the prs, writing docs?

**Comment by sadiksha** [comment]
Hi, 
I am also willing to help you. Like @nirnaeth said, how would it work? Should I take on an issue and work on it? 

Thanks.

**Comment by jkeam** [comment]
👍 

We've got a few issues outstanding.  I'd say grab one and open a PR for it.  Thanks for helping!

**Comment by bf4** [comment]
@nirnaeth @sadiksha If you make a PR that looks good, I can add you.  In the meantime, take a look at the outstanding issues. :)

**Comment by nirnaeth** [comment]
on it :)

**Comment by aashish** [comment]
Hi, I would like to help. Let me know about an issue to work.

**Comment by andynu** [comment]
Hi, I'm interested in helping as well. There is a bunch of good work sitting on master. How can I help get us to v4.13?

**Comment by sapna-prajapati** [comment]
Let me know what is the issue, would like to fix it.

**Comment by pboling** [comment]
If you want to help:

Work on open issues:
https://github.com/metricfu/metric_fu/issues

Review Pull Requests:
https://github.com/metricfu/metric_fu/pulls

**Comment by bf4** [comment]
Anyone want a release? Or plan what's next?

**Comment by andynu** [comment]
Hi @bf4 , I'm still interested in the 4.13 release. There are fixes already on master that would be useful to me. Releasing just that would be awesome.

Are there other things you'd like in this release? I looked through the tickets a bit this morning, and many of them are new feature work, or involve the online tooling (travis, launchy) which I'm not sure how to help with. #262 seems like a fixable bug; I could take a stab at that.

**Comment by jkeam** [comment]
Same, I'd love a release :)

**Comment by andynu** [comment]
Having spent some time in the repo this evening I do have some interest in planning what's next. And what's next in my mind is nothing drastic, mostly just moving things forward to support the newest versions of ruby, and the newest versions of the metric tools.

Tests passed in more recent rubies (2.3.x, 2.4.x, and 2.5.x). I think we could alter the Gemfile to be a bit more permissive about new ruby versions, locking down the gem requirements only for older constraints and being hopeful about the future.

I'm also willing to through the issues and labeling them.

**Comment by jkeam** [comment]
Love the idea!

**Comment by bf4** [comment]
the alternative, is to sunset the project and recommend more active ones like pronto ( see https://github.com/metricfu/metric_fu/wiki/Code-Tools though I haven't updated it in a bit, the only new ones I can think of offhand are simplecov alternatives)

If people are really gung ho on working here, and I started because it was fun, so that's enough of a reason, here's what I've been thinking of doing: simplify each piece by building multiple gems in one project like https://github.com/kaminari/kaminari

- kaminari https://github.com/kaminari/kaminari/blob/master/kaminari.gemspec
  - kaminari-actionview https://github.com/kaminari/kaminari/blob/master/kaminari-actionview/kaminari-actionview.gemspec
  - kaminari-activerecord https://github.com/kaminari/kaminari/blob/master/kaminari-activerecord/kaminari-activerecord.gemspec
  - kaminari-core https://github.com/kaminari/kaminari/blob/master/kaminari-core/kaminari-core.gemspec

I had put a lot of thought and effort into making metric fu more modular but never finished. It should be pretty easy to break up metric_fu by components and make sure each is independent.  This would also help you release changes for e.g. reek more easily 

Ultimately, what I would have liked to have done would be to promote a common interface for metrics tools to take in the ASTs generated by either ruby_parser or parser, so that you'd only have to parse once.  I spiked some work in Reek to do this once, but it's gone now, and I think there's a PR or something for flay?

**Comment by andynu** [comment]
Perhaps it is time to sunset this project and more actively recommend the
alternatives. I can't say I'm gung ho; spare time is hard to come by. I
have loved this project though. The nice wrapper around all these tools and
the continuity of this history charts were great. Thanks again for all your
work on this.

**Comment by vraravam** [comment]
I'm also interested in this project - none of the alternatives seem to match up. What can we do to revive this codebase?

**Comment by jmarkbrooks** [comment]
I'm up to assist.  What is needed?

**Comment by etagwerker** [comment]
Hi @bf4 and all, I'm interested in co-maintaining `metric_fu` with the rest of the people who showed interest here. 

I went ahead and submitted these PRs:

- https://github.com/metricfu/metric_fu/pull/308 which fixes #307 
- https://github.com/metricfu/metric_fu/pull/306 which fixes #305 

I'd love to get some feedback on those. 😃

**Comment by bf4** [comment]
sigh, sorry I'm not so present on this. Basically, before I give someone commit, I want to look at their code... and I haven't done much of the latter so I haven't done much of the former. Giving rubygems permissions for releasing new versions is more serious, so that'll take a little more attention on my part before I trust you enough :)

**Comment by jacobbeasley** [comment]
Somebody (or a group of people) probably just need to fork this repo at this point.

**Comment by bf4** [comment]
@jacobbeasley the issue isn't a need for a fork (though you're welcome to).  If you can maintain it and are willing you, I'll give you commit. And if that looks good, I'll give you rubygems ownership.

**Comment by etagwerker** [comment]
If anyone is interested, I started this fork: https://rubygems.org/gems/fastruby-metric_fu. It fixed #305 which is what was blocking me.

**Comment by bronzdoc** [comment]
Hello everyone.

`metric_fu 4.13.0` was just released. The company I work for [OmbuLabs](https://www.ombulabs.com) will be sponsoring me and @etagwerker to dedicate some hours a month in the develop of metric_fu.

Thanks to @bf4 and the maintainers of metric_fu in the past for the the work and the trust on us. I hope we can help keep moving the project forward.

Please if you would like to help maintaining metric_fu contact any of @etagwerker or me thanks!
