### ISSUE TITLE
Sort out the VersionEye issues

### ISSUE THREAD

**Issue by jkeam** [metricfu/metric_fu#281]
The VersionEye thing is doing a few wonky things:
- [x]  rubycop isn't being picked up.  The version that fisheye is finding from our gemfile is ":local_development]", which I bet is a parsing error on their part.  This is how we are including it:
  `gem "rubocop", platforms: :mri, groups: [:test, :local_development]` I bet they are just slicing off the last word, but I haven't checked their code to see what they are actually doing.
- [x]  jruby-openssl is just not getting picked up for some reason:
  https://github.com/jruby/jruby-openssl/blob/master/LICENSE.txt
- [x] rb-notifu the author has claimed MIT, but hasn't added the LICENSE file yet, so this is a valid error.
- [x] terminal-notifier-guard is also not getting picked up:
  https://github.com/Codaisseur/terminal-notifier-guard/blob/master/LICENSE

**Comment by jkeam** [comment]
VersionEye has been dropped so let's consider this issue closed. :)

**Comment by jkeam** [comment]
I take it back.  I thought it was gone, but still seeing a few issues when opening PRs.

![version_eye_issues](https://cloud.githubusercontent.com/assets/48856/19958838/a195b0b6-a178-11e6-92c9-f34c53d5a9c8.png)

**Comment by bf4** [comment]
@jkeam I believe I just disabled and removed version eye. It shouldn't be failing builds like this.
