### ISSUE TITLE
Bundler 1.14 load of native gem

### ISSUE THREAD

**Issue by bergholdt** [metricfu/metric_fu#297]
I have new builds failing on travis because of new bundler 1.14 released 20. jan.

This bundler version has a new way of loading native gems so our JRuby build will fail.
https://travis-ci.org/bergholdt/metric_fu/builds/193916594

I can see issues on bundler repo https://github.com/bundler/bundler/issues/5337 related to this

A work a round is to force 1.13.7 on travis
https://github.com/bergholdt/metric_fu/compare/8a9965b76d80...04e1917e175e
https://travis-ci.org/bergholdt/metric_fu/builds/194016131

**Comment by jkeam** [comment]
I'm worried about people running JRuby and Bundler 1.14.  Is there anyway we could help them?  Or maybe just put a note in the README so users know that this is the workaround until we can figure out a solution?

**Comment by bergholdt** [comment]
Agree that we should make it possible for users to use whatever bundler version they need. 

But I do hope that it's an error in bundler and they help us solve this 😊 

This issue https://github.com/bundler/bundler/issues/5340 has a PR that looks like to fix it. 

Think we should await this before making more gemfile rules.

**Comment by bf4** [comment]
@bergholdt freezing the bundler version in travis seems like what the end user would do until the bundler issue is resolved. It's not uncommon to do that in CI.  I'm 👍 and leave a comment referencing this PR, say 'remove when #297 resolved', or something like that.

**Comment by bergholdt** [comment]
Builds now pass on bundler 1.14.3 on both Travis and AppVeyor
