### ISSUE TITLE
`master` build seems to be broken in Travis CI

### ISSUE THREAD

**Issue by etagwerker** [metricfu/metric_fu#307]
Hi there, 

It seems that `master` is failing in Travis CI. The last successful build was about 3 years ago: https://travis-ci.org/metricfu/metric_fu/builds/173060468

I just submitted a PR with "minor" changes and it seems to fail when trying to `bundle install` -- See: https://travis-ci.org/metricfu/metric_fu/builds/584337697

**Comment by bf4** [comment]
@etagwerker you have a bunch of open prs.. maybe point me to them in order here?

**Comment by etagwerker** [comment]
@bf4 Sure thing: 

1. https://github.com/metricfu/metric_fu/pull/310 -- this one removes unwanted specific version declarations which are causing `bundle install` to fail after git cloning the project

1. https://github.com/metricfu/metric_fu/pull/308 -- this one seems to be approved by you and ready to be merged. It fixes Travis CI by updating its configuration to use rubies that haven't been EOLed

1. Once you've merged the first two, I can continue extracting things out of https://github.com/metricfu/metric_fu/pull/306. This one has many changes and you requested to extract more pull requests out of it. The next PR I'm going to extract is going to fix https://github.com/metricfu/metric_fu/issues/312
