### ISSUE TITLE
Appveyor builds are not working 

### ISSUE THREAD

**Issue by etagwerker** [metricfu/metric_fu#312]
Hey @bf4, 

Creating this issue to keep track of the Appveyor issues. More here: https://github.com/metricfu/metric_fu/pull/310#issuecomment-533945439

You can see that the Travis CI test suite passes over here: https://github.com/metricfu/metric_fu/pull/308 

In that same PR, Appveyor fails because it requires a specific version of `bundler`: https://ci.appveyor.com/project/bf4/metric-fu/builds/27586678

```
Build started
2git clone -q https://github.com/metricfu/metric_fu.git C:\projects\metric-fu
3git fetch -q origin +refs/pull/308/merge:
4git checkout -qf FETCH_HEAD
5Running Install scripts
6set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
7gem install bundler
8ERROR:  Error installing bundler:
9	The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
10	bundler requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
11Command exited with code 1
```

Part of the solution is in #306. I'll try to extract those changes and submit a new PR to fix this issue.

**Comment by bronzdoc** [comment]
Should be fixed now.

https://github.com/metricfu/metric_fu/pull/314
https://github.com/metricfu/metric_fu/pull/318
